# Generated by Django 4.1.1 on 2022-09-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_questions_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='description',
            field=models.CharField(blank=True, db_index=True, max_length=1000, null=True),
        ),
    ]
