# Generated by Django 4.1.1 on 2022-09-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_test_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(db_index=True, error_messages='Test with that name already exists', max_length=100, unique=True),
        ),
    ]
