# Generated by Django 4.1.1 on 2022-09-13 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_categories_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_test', to='main_app.test'),
        ),
    ]
