# Generated by Django 4.1.1 on 2022-09-13 19:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_questions_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='time_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
