# Generated by Django 4.1.1 on 2022-09-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_test_time_create_test_time_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
