# Generated by Django 4.1.1 on 2022-09-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_test_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='answer_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='answer_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
