# Generated by Django 4.1.1 on 2022-09-21 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_questions_answer_2_alter_questions_answer_3_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questions',
            unique_together={('question', 'test')},
        ),
    ]
