# Generated by Django 4.1.1 on 2022-09-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_questions_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='questions',
            name='unique questions',
        ),
        migrations.AddConstraint(
            model_name='questions',
            constraint=models.UniqueConstraint(fields=('test_id', 'question'), name='unique_questions'),
        ),
    ]
