# Generated by Django 4.1.1 on 2022-09-22 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_remove_questions_unique questions_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='questions',
            name='unique_questions',
        ),
    ]
