# Generated by Django 4.1.1 on 2022-09-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_remove_questions_unique_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='questions',
            constraint=models.UniqueConstraint(fields=('test_id', 'question'), name='unique_questions'),
        ),
    ]
