# Generated by Django 4.1.1 on 2022-09-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_rename_show_result_test_show_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='value',
            field=models.IntegerField(default=1),
        ),
    ]
