# Generated by Django 4.1.1 on 2022-10-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_passedtests_max_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='access_by_link',
            field=models.BooleanField(default=True),
        ),
    ]
