# Generated by Django 4.1.1 on 2022-10-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_test_access_by_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='answer_1',
            field=models.CharField(default='cat', max_length=255),
            preserve_default=False,
        ),
    ]
