# Generated by Django 4.1.1 on 2022-10-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_alter_questions_answer_1'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='questions',
            constraint=models.UniqueConstraint(fields=('question', 'correct_answer', 'answer_1', 'answer_2', 'answer_3'), name='unique_answers', violation_error_message='The answer is already in the question.'),
        ),
    ]
