# Generated by Django 4.1.1 on 2022-10-11 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_questions_unique_answers'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='questions',
            name='unique_answers',
        ),
    ]
