# Generated by Django 4.1.1 on 2022-10-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_alter_passedtests_grade_alter_passedtests_max_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passedtests',
            name='grade',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='passedtests',
            name='max_grade',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
