# Generated by Django 4.1.1 on 2022-11-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0029_alter_passedtests_grade_alter_passedtests_max_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='passedtests',
            name='correct_answers',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='passedtests',
            name='grade',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
