# Generated by Django 4.1.1 on 2022-11-04 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0030_passedtests_correct_answers_alter_passedtests_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passedtests',
            old_name='correct_answers',
            new_name='score',
        ),
    ]
