# Generated by Django 4.1.1 on 2022-11-09 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0032_alter_passedtests_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passedtests',
            old_name='max_grade',
            new_name='max_score',
        ),
    ]
